# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18.x'
        - name: Install dependencies
          run: npm install
        - name: Run test
          run: npm test
        - name: Check Job Status status and fail if they are red
          if: env.WORKFLOW_CONCLUSION == 'failure'
          run: exit 1
          
 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
             heroku_api_key: ${{secrets.HEROKU_API_KEY}}
             heroku_app_name: 'appnodedeploy2'
             heroku_email: "igna7_17@hotmail.com"
             
